### BeautifulSoup 
* select() 함수 사용
* melon 100 chart 데이터 파싱

In [1]:
import re
import requests
from bs4 import BeautifulSoup

url = 'https://www.melon.com/chart/index.htm'

headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# 노래 상세정보 song_url = f'https://www.melon.com/song/detail.htm?songId={song_id}'

res = requests.get(url, headers=headers)
if not res.ok:
    print(f'Error Code = {res.status_code}')
    exit()

soup = BeautifulSoup(res.text, 'html.parser')
# <div class="wrap_song_info"> 
#   <a href="javascript:melon.play.playSong('1000002721',37928381);" title="LOVE ATTACK 재생">LOVE ATTACK</a>
atag_list = soup.select("div.wrap_song_info a[href*='playSong']")
print(len(atag_list))

# [{},{}]
#100곡의 Song List
song_list = []
for idx,atag in enumerate(atag_list,1):
    #1곡 song dict
    song_dict = {}
    #Song 제목
    song_dict['title'] = atag.text
    #href 링크 추출
    href = atag['href']
    matched = re.search(r'(\d+)\);',href)
    if matched:
        #print(matched.group(0), matched.group(1))  602024048); 602024048
        song_id = matched.group(1)
    #Song ID
    song_dict['id'] = song_id  
    #Song URL
    song_url = f'https://www.melon.com/song/detail.htm?songId={song_id}'
    song_dict['url'] = song_url    
    print(f'{idx} = {song_dict}')

    #song_dict를 song_list에 append
    song_list.append(song_dict)

100
1 = {'title': 'LOVE ATTACK', 'id': '37928381', 'url': 'https://www.melon.com/song/detail.htm?songId=37928381'}
2 = {'title': '갑자기', 'id': '602024048', 'url': 'https://www.melon.com/song/detail.htm?songId=602024048'}
3 = {'title': 'REDRED', 'id': '601807965', 'url': 'https://www.melon.com/song/detail.htm?songId=601807965'}
4 = {'title': 'LEMONADE', 'id': '602115220', 'url': 'https://www.melon.com/song/detail.htm?songId=602115220'}
5 = {'title': 'Pretty Girl', 'id': '602450078', 'url': 'https://www.melon.com/song/detail.htm?songId=602450078'}
6 = {'title': 'It′s Me', 'id': '601899271', 'url': 'https://www.melon.com/song/detail.htm?songId=601899271'}
7 = {'title': 'Deja Vu', 'id': '39231685', 'url': 'https://www.melon.com/song/detail.htm?songId=39231685'}
8 = {'title': '만찬가', 'id': '602377105', 'url': 'https://www.melon.com/song/detail.htm?songId=602377105'}
9 = {'title': '캐치 캐치', 'id': '601479669', 'url': 'https://www.melon.com/song/detail.htm?songId=601479669'}
10 = {'title': 'BAD', 'id': '602322595', 'url': 'https://www.melon.com/song/detail.htm?songId=602322595'}
11 = {'title': 'Drowning', 'id': '36397952', 'url': 'https://www.melon.com/song/detail.htm?songId=36397952'}
12 = {'title': '여름아 부탁해', 'id': '602552833', 'url': 'https://www.melon.com/song/detail.htm?songId=602552833'}
13 = {'title': '사랑하게 될 거야', 'id': '36730261', 'url': 'https://www.melon.com/song/detail.htm?songId=36730261'}
14 = {'title': 'RUDE!', 'id': '601332163', 'url': 'https://www.melon.com/song/detail.htm?songId=601332163'}
15 = {'title': '소문의 낙원', 'id': '601719413', 'url': 'https://www.melon.com/song/detail.htm?songId=601719413'}
16 = {'title': 'Lemon Tang', 'id': '602313594', 'url': 'https://www.melon.com/song/detail.htm?songId=602313594'}
17 = {'title': 'Good Goodbye', 'id': '600287375', 'url': 'https://www.melon.com/song/detail.htm?songId=600287375'}
18 = {'title': '0+0', 'id': '39504779', 'url': 'https://www.melon.com/song/detail.htm?songId=39504779'}
19 = {'title': '기쁨, 슬픔, 아름다운 마음', 'id': '601719416', 'url': 'https://www.melon.com/song/detail.htm?songId=601719416'}
20 = {'title': '타임캡슐', 'id': '600299706', 'url': 'https://www.melon.com/song/detail.htm?songId=600299706'}
21 = {'title': '한 페이지가 될 수 있게', 'id': '31927275', 'url': 'https://www.melon.com/song/detail.htm?songId=31927275'}
22 = {'title': '404 (New Era)', 'id': '601013499', 'url': 'https://www.melon.com/song/detail.htm?songId=601013499'}
23 = {'title': 'Heavy Serenade', 'id': '601879407', 'url': 'https://www.melon.com/song/detail.htm?songId=601879407'}
24 = {'title': '생각을 멈추다 보면', 'id': '36985781', 'url': 'https://www.melon.com/song/detail.htm?songId=36985781'}
25 = {'title': 'BANG BANG', 'id': '601237102', 'url': 'https://www.melon.com/song/detail.htm?songId=601237102'}
26 = {'title': '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'id': '32061975', 'url': 'https://www.melon.com/song/detail.htm?songId=32061975'}
27 = {'title': 'Popcorn', 'id': '37473973', 'url': 'https://www.melon.com/song/detail.htm?songId=37473973'}
28 = {'title': 'HAPPY', 'id': '37323944', 'url': 'https://www.melon.com/song/detail.htm?songId=37323944'}
29 = {'title': '어제보다 슬픈 오늘', 'id': '38733032', 'url': 'https://www.melon.com/song/detail.htm?songId=38733032'}
30 = {'title': 'Blue Valentine', 'id': '600243411', 'url': 'https://www.melon.com/song/detail.htm?songId=600243411'}
31 = {'title': '너의 모든 순간', 'id': '4446485', 'url': 'https://www.melon.com/song/detail.htm?songId=4446485'}
32 = {'title': '너에게 닿기를', 'id': '38626852', 'url': 'https://www.melon.com/song/detail.htm?songId=38626852'}
33 = {'title': '뛰어(JUMP)', 'id': '39298775', 'url': 'https://www.melon.com/song/detail.htm?songId=39298775'}
34 = {'title': 'Less than a Lover', 'id': '602584682', 'url': 'https://www.melon.com/song/detail.htm?songId=602584682'}
35 = {'title': "Surfin' Boy", 'id': '602683997', 'url': 'https://www.melon.com/song/detail.htm?songId=602683997'}
36 = {'title': '모르시나요(PROD.로코베리)', 'id': '38429074', 'url': 'https://www.melon.com/song/detail.htm?songId=38429074'}
37 = {'title': 'SWIM', 'id': '601555642', 'url': 'https://www.melon.com/song/detail.htm?songId=601555642'}
38 = {'title': '소나기', 'id': '37390939', 'url': 'https://www.melon.com/song/detail.htm?songId=37390939'}
39 = {'title': 'Whiplash', 'id': '38123332', 'url': 'https://www.melon.com/song/detail.htm?songId=38123332'}
40 = {'title': '멸종위기사랑', 'id': '39307948', 'url': 'https://www.melon.com/song/detail.htm?songId=39307948'}
41 = {'title': '내게 사랑이 뭐냐고 물어본다면', 'id': '38104031', 'url': 'https://www.melon.com/song/detail.htm?songId=38104031'}
42 = {'title': 'Golden', 'id': '39166708', 'url': 'https://www.melon.com/song/detail.htm?songId=39166708'}
43 = {'title': 'toxic till the end', 'id': '38300904', 'url': 'https://www.melon.com/song/detail.htm?songId=38300904'}
44 = {'title': '천상연', 'id': '37228861', 'url': 'https://www.melon.com/song/detail.htm?songId=37228861'}
45 = {'title': 'HOME SWEET HOME (feat. 태양, 대성)', 'id': '38242510', 'url': 'https://www.melon.com/song/detail.htm?songId=38242510'}
46 = {'title': 'Seven (feat. Latto) - Clean Ver.', 'id': '36617841', 'url': 'https://www.melon.com/song/detail.htm?songId=36617841'}
47 = {'title': '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))', 'id': '36699489', 'url': 'https://www.melon.com/song/detail.htm?songId=36699489'}
48 = {'title': '청춘만화', 'id': '38071559', 'url': 'https://www.melon.com/song/detail.htm?songId=38071559'}
49 = {'title': '사랑은 늘 도망가', 'id': '34061322', 'url': 'https://www.melon.com/song/detail.htm?songId=34061322'}
50 = {'title': '첫 만남은 계획대로 되지 않아', 'id': '37140709', 'url': 'https://www.melon.com/song/detail.htm?songId=37140709'}
51 = {'title': 'Dynamite', 'id': '32872978', 'url': 'https://www.melon.com/song/detail.htm?songId=32872978'}
52 = {'title': '모든 날, 모든 순간 (Every day, Every Moment)', 'id': '30962526', 'url': 'https://www.melon.com/song/detail.htm?songId=30962526'}
53 = {'title': '그대 작은 나의 세상이 되어', 'id': '33241003', 'url': 'https://www.melon.com/song/detail.htm?songId=33241003'}
54 = {'title': 'like JENNIE', 'id': '38629386', 'url': 'https://www.melon.com/song/detail.htm?songId=38629386'}
55 = {'title': 'Vitamin ME', 'id': '602540014', 'url': 'https://www.melon.com/song/detail.htm?songId=602540014'}
56 = {'title': '봄 내음보다 너를', 'id': '33411344', 'url': 'https://www.melon.com/song/detail.htm?songId=33411344'}
57 = {'title': 'Hype Boy', 'id': '35454426', 'url': 'https://www.melon.com/song/detail.htm?songId=35454426'}
58 = {'title': 'Runaway', 'id': '601719493', 'url': 'https://www.melon.com/song/detail.htm?songId=601719493'}
59 = {'title': 'STYLE', 'id': '39161085', 'url': 'https://www.melon.com/song/detail.htm?songId=39161085'}
60 = {'title': '주저하는 연인들을 위해', 'id': '31666417', 'url': 'https://www.melon.com/song/detail.htm?songId=31666417'}
61 = {'title': 'Pop Off Pop Off', 'id': '602732384', 'url': 'https://www.melon.com/song/detail.htm?songId=602732384'}
62 = {'title': 'APT.', 'id': '38120327', 'url': 'https://www.melon.com/song/detail.htm?songId=38120327'}
63 = {'title': 'WDA (Whole Different Animal) (Feat. G-DRAGON)', 'id': '601968268', 'url': 'https://www.melon.com/song/detail.htm?songId=601968268'}
64 = {'title': '나는 반딧불', 'id': '38123338', 'url': 'https://www.melon.com/song/detail.htm?songId=38123338'}
65 = {'title': '예뻤어', 'id': '30232719', 'url': 'https://www.melon.com/song/detail.htm?songId=30232719'}
66 = {'title': '봄날', 'id': '30244931', 'url': 'https://www.melon.com/song/detail.htm?songId=30244931'}
67 = {'title': '사랑인가 봐', 'id': '34657844', 'url': 'https://www.melon.com/song/detail.htm?songId=34657844'}
68 = {'title': '입춘', 'id': '34753369', 'url': 'https://www.melon.com/song/detail.htm?songId=34753369'}
69 = {'title': '청혼하지 않을 이유를 못 찾았어', 'id': '37375706', 'url': 'https://www.melon.com/song/detail.htm?songId=37375706'}
70 = {'title': '오늘만 I LOVE YOU', 'id': '38426197', 'url': 'https://www.melon.com/song/detail.htm?songId=38426197'}
71 = {'title': 'REBEL HEART', 'id': '38444825', 'url': 'https://www.melon.com/song/detail.htm?songId=38444825'}
72 = {'title': 'Magnetic', 'id': '37347911', 'url': 'https://www.melon.com/song/detail.htm?songId=37347911'}
73 = {'title': 'Body to Body', 'id': '601555636', 'url': 'https://www.melon.com/song/detail.htm?songId=601555636'}
74 = {'title': 'Welcome to the Show', 'id': '37323943', 'url': 'https://www.melon.com/song/detail.htm?songId=37323943'}
75 = {'title': 'FAMOUS', 'id': '39156202', 'url': 'https://www.melon.com/song/detail.htm?songId=39156202'}
76 = {'title': 'Die With A Smile', 'id': '37901626', 'url': 'https://www.melon.com/song/detail.htm?songId=37901626'}
77 = {'title': 'Love Love Love (Feat. Yoong Jin Of Casker)', 'id': '1556553', 'url': 'https://www.melon.com/song/detail.htm?songId=1556553'}
78 = {'title': '다정히 내 이름을 부르면', 'id': '33496587', 'url': 'https://www.melon.com/song/detail.htm?songId=33496587'}
79 = {'title': '사랑은 봄비처럼...이별은 겨울비처럼...', 'id': '1121123', 'url': 'https://www.melon.com/song/detail.htm?songId=1121123'}
80 = {'title': '시작의 아이 ❍', 'id': '39566906', 'url': 'https://www.melon.com/song/detail.htm?songId=39566906'}
81 = {'title': '헤어지자 말해요', 'id': '36382580', 'url': 'https://www.melon.com/song/detail.htm?songId=36382580'}
82 = {'title': 'SPAGHETTI (feat. j-hope of BTS)', 'id': '600354699', 'url': 'https://www.melon.com/song/detail.htm?songId=600354699'}
83 = {'title': 'BOOMPALA', 'id': '602066108', 'url': 'https://www.melon.com/song/detail.htm?songId=602066108'}
84 = {'title': 'Shut The Door', 'id': '602606494', 'url': 'https://www.melon.com/song/detail.htm?songId=602606494'}
85 = {'title': 'Love wins all', 'id': '37145732', 'url': 'https://www.melon.com/song/detail.htm?songId=37145732'}
86 = {'title': '에피소드', 'id': '37053556', 'url': 'https://www.melon.com/song/detail.htm?songId=37053556'}
87 = {'title': 'Flower', 'id': '38635449', 'url': 'https://www.melon.com/song/detail.htm?songId=38635449'}
88 = {'title': '이 밤을 빌려 말해요', 'id': '600791038', 'url': 'https://www.melon.com/song/detail.htm?songId=600791038'}
89 = {'title': '달리 표현할 수 없어요', 'id': '600359330', 'url': 'https://www.melon.com/song/detail.htm?songId=600359330'}
90 = {'title': '눈을 감아도(2026)', 'id': '601379618', 'url': 'https://www.melon.com/song/detail.htm?songId=601379618'}
91 = {'title': 'ONE MORE TIME', 'id': '600513208', 'url': 'https://www.melon.com/song/detail.htm?songId=600513208'}
92 = {'title': '순간을 영원처럼', 'id': '39765727', 'url': 'https://www.melon.com/song/detail.htm?songId=39765727'}
93 = {'title': '우리들의 블루스', 'id': '34908740', 'url': 'https://www.melon.com/song/detail.htm?songId=34908740'}
94 = {'title': 'I AM', 'id': '36356993', 'url': 'https://www.melon.com/song/detail.htm?songId=36356993'}
95 = {'title': 'FOCUS', 'id': '600320356', 'url': 'https://www.melon.com/song/detail.htm?songId=600320356'}
96 = {'title': 'BLACKHOLE', 'id': '601356371', 'url': 'https://www.melon.com/song/detail.htm?songId=601356371'}
97 = {'title': 'Soda Pop', 'id': '39166705', 'url': 'https://www.melon.com/song/detail.htm?songId=39166705'}
98 = {'title': 'OVERDRIVE', 'id': '600280518', 'url': 'https://www.melon.com/song/detail.htm?songId=600280518'}
99 = {'title': 'Hooligan', 'id': '601555637', 'url': 'https://www.melon.com/song/detail.htm?songId=601555637'}
100 = {'title': '2.0', 'id': '601555640', 'url': 'https://www.melon.com/song/detail.htm?songId=601555640'}

In [2]:
#len(song_list)
song_list[:2]

[{'title': 'LOVE ATTACK',
  'id': '37928381',
  'url': 'https://www.melon.com/song/detail.htm?songId=37928381'},
 {'title': '갑자기',
  'id': '602024048',
  'url': 'https://www.melon.com/song/detail.htm?songId=602024048'}]

### 곡상세 정보 추출하기

In [3]:
import re
import requests
from bs4 import BeautifulSoup
from pprint import pprint

headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# 좋아요 건수 가져오기 ajax_url = f'https://www.melon.com/commonlike/getSongLike.json?contsIds={song_id}'

# Song 100곡의 상세정보 목록을 저장할 list 선언
song_lyric_list = list()
print('===> 100 곡 노래 파싱 시작')
for idx,song in enumerate(song_list,1):
    print(f'==> {idx} {song['title']}')
    # Song 1곡의 상세정보를 저장할 dict 선언
    song_lyric_dict = dict()
    
    res = requests.get(song['url'], headers=headers)
    if res.ok:
        soup = BeautifulSoup(res.text,'html.parser')
        # Song 제목
        song_lyric_dict['곡명'] = song['title']
        
        singer_span = soup.select_one("a[href*='goArtistDetail'] span")
        song_lyric_dict['가수'] = singer_span.text

        song_dd = soup.select('div.meta dd') #song_dd는 ResultSet타입, song_dd[0]는 Tag 타입
        if song_dd:
            song_lyric_dict['앨범'] = song_dd[0].get_text(strip=True).replace('\xa0', ' ')
            song_lyric_dict['발매일'] = song_dd[1].text
            song_lyric_dict['장르'] = song_dd[2].text
        
        # Song 상세정보 url 저장
        song_lyric_dict['detail_url'] = song['url']
        
        # 좋아요 건수
        song_id = song['id']
        ajax_url = f'https://www.melon.com/commonlike/getSongLike.json?contsIds={song_id}'
        res = requests.get(ajax_url, headers=headers)
        '''
        {
            ``    "contsLike": [
                    {
                        "CONTSID": 600287375,
                        "LIKEYN": "N",
                        "SUMMCNT": 109704
                    }
                ],
                "httpDomain": "http://www.melon.com",
                "httpsDomain": "https://www.melon.com",
                "staticDomain": "https://static.melon.co.kr"
            }``
        '''
        if res.ok:
            song_lyric_dict['좋아요'] = res.json()['contsLike'][0]['SUMMCNT']

        # 노래 가사     
        lyric_div = soup.select('div#d_video_summary')
        if lyric_div:
            lyric = lyric_div[0].text
        else:
            lyric = ''    

        # \n\r\t 특수문자를 찾는 Pattern객체 생성
        pattern = re.compile(r'[\n\r\t]')
        song_lyric_dict['가사'] = pattern.sub('', lyric)

        #print(song_lyric_dict)
        # song list에 노래상세 정보 dict를 저장하기
        song_lyric_list.append(song_lyric_dict)
    else:
        print(f'Error 코드 = {res.status_code}')    

print(len(song_lyric_list))
pprint(song_lyric_list[98:])
print('===> 100 곡 노래 파싱 끝')

===> 100 곡 노래 파싱 시작
==> 1 LOVE ATTACK
==> 2 갑자기
==> 3 REDRED
==> 4 LEMONADE
==> 5 Pretty Girl
==> 6 It′s Me
==> 7 Deja Vu
==> 8 만찬가
==> 9 캐치 캐치
==> 10 BAD
==> 11 Drowning
==> 12 여름아 부탁해
==> 13 사랑하게 될 거야
==> 14 RUDE!
==> 15 소문의 낙원
==> 16 Lemon Tang
==> 17 Good Goodbye
==> 18 0+0
==> 19 기쁨, 슬픔, 아름다운 마음
==> 20 타임캡슐
==> 21 한 페이지가 될 수 있게
==> 22 404 (New Era)
==> 23 Heavy Serenade
==> 24 생각을 멈추다 보면
==> 25 BANG BANG
==> 26 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지
==> 27 Popcorn
==> 28 HAPPY
==> 29 어제보다 슬픈 오늘
==> 30 Blue Valentine
==> 31 너의 모든 순간
==> 32 너에게 닿기를
==> 33 뛰어(JUMP)
==> 34 Less than a Lover
==> 35 Surfin' Boy
==> 36 모르시나요(PROD.로코베리)
==> 37 SWIM
==> 38 소나기
==> 39 Whiplash
==> 40 멸종위기사랑
==> 41 내게 사랑이 뭐냐고 물어본다면
==> 42 Golden
==> 43 toxic till the end
==> 44 천상연
==> 45 HOME SWEET HOME (feat. 태양, 대성)
==> 46 Seven (feat. Latto) - Clean Ver.
==> 47 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))
==> 48 청춘만화
==> 49 사랑은 늘 도망가
==> 50 첫 만남은 계획대로 되지 않아
==> 51 Dynamite
==> 52 모든 날, 모든 순간 (Every day, Every Moment)
==> 53 그대 작은 나의 세상이 되어
==> 54 like JENNIE
==> 55 Vitamin ME
==> 56 봄 내음보다 너를
==> 57 Hype Boy
==> 58 Runaway
==> 59 STYLE
==> 60 주저하는 연인들을 위해
==> 61 Pop Off Pop Off
==> 62 APT.
==> 63 WDA (Whole Different Animal) (Feat. G-DRAGON)
==> 64 나는 반딧불
==> 65 예뻤어
==> 66 봄날
==> 67 사랑인가 봐
==> 68 입춘
==> 69 청혼하지 않을 이유를 못 찾았어
==> 70 오늘만 I LOVE YOU
==> 71 REBEL HEART
==> 72 Magnetic
==> 73 Body to Body
==> 74 Welcome to the Show
==> 75 FAMOUS
==> 76 Die With A Smile
==> 77 Love Love Love (Feat. Yoong Jin Of Casker)
==> 78 다정히 내 이름을 부르면
==> 79 사랑은 봄비처럼...이별은 겨울비처럼...
==> 80 시작의 아이 ❍
==> 81 헤어지자 말해요
==> 82 SPAGHETTI (feat. j-hope of BTS)
==> 83 BOOMPALA
==> 84 Shut The Door
==> 85 Love wins all
==> 86 에피소드
==> 87 Flower
==> 88 이 밤을 빌려 말해요
==> 89 달리 표현할 수 없어요
==> 90 눈을 감아도(2026)
==> 91 ONE MORE TIME
==> 92 순간을 영원처럼
==> 93 우리들의 블루스
==> 94 I AM
==> 95 FOCUS
==> 96 BLACKHOLE
==> 97 Soda Pop
==> 98 OVERDRIVE
==> 99 Hooligan
==> 100 2.0
100
[{'detail_url': 'https://www.melon.com/song/detail.htm?songId=601555637',
  '가사': 'Watch this, watch this beat goin’ hooligan We pop out, we actin’ a '
        'fool again HooliganWatch this, watch this beat goin’ hooliganWhy this '
        'bassline slappin’ so rudeDrop it lower than chopped and '
        'screwedHooliganWatch this, watch this beat goin’ hooliganMan, I’m '
        '’bout to blow a fuse 통제불능, 머리 춤뛰어 미친놈인 듯Me everywhere, 얼쑤Somebody '
        'moveSomebody move다들 모여 하나 둘 I can never ever chooseEvery one o’ you a '
        'muse Crowd lookin’ like a campus Beat drop 우린 dancin’Watch this, '
        'watch this beat goin’ hooligan We pop out, we actin’ a fool again '
        'HooliganWatch this, watch this beat goin’ hooliganWhy this bassline '
        'slappin’ so rudeDrop it lower than chopped and screwedHooliganWatch '
        'this, watch this beat goin’ hooliganI go cuckoo crazy loco save me '
        'Like El Cucuy 굳이 말 안 해도 알잖아 Hooligan, like hooligan때려 부숴 like '
        'hooligan시간 됐으니 좀 비켜 좀All clear 이상 무Take you outTake you outWhat’s the '
        'future?Where’s the now?  This is internationalMake it '
        'unforgettableWatch this, watch this beat goin’ hooligan We pop out, '
        'we actin’ a fool again HooliganWatch this, watch this beat goin’ '
        'hooliganWe the mess, gonna get a bigger mop hereThis that K, gotta '
        'get a better pop hereYou gon’ hear this one playin’ round the clock, '
        'yeahRound the clock clock clock clockWhy this bassline slappin’ so '
        'rudeDrop it lower than chopped and screwedHooliganWatch this, watch '
        'this beat goin’ hooliganWhy this bassline slappin’ so rudeDrop it '
        'lower than chopped and screwedHooliganWatch this, watch this beat '
        'goin’ hooligan ',
  '가수': '방탄소년단',
  '곡명': 'Hooligan',
  '발매일': '2026.03.20',
  '앨범': 'ARIRANG',
  '장르': '랩/힙합',
  '좋아요': 33627},
 {'detail_url': 'https://www.melon.com/song/detail.htm?songId=601555640',
  '가사': '그래 방탄처럼 그게 말은 쉽지우린 뜀틀 누가 맨날 뛰어넘니웃기기는 한데 사실 안 웃기지10년은 말야 어림 반 푼어치Stop, '
        'rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock knock '
        'knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do Ay ay ay 그래, 기분 마치 '
        'brand new Spec 다른 step, 뛰지 않는 step twoTwo, two point oh 업데이트된 후여기저기 또 '
        '한 번 일냈네 10 out of 10, 10 이젠 버려, 못 쓸 폐품 수거하러 가여유 있게 다시 수고하러 Stop, '
        'rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock knock '
        'knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do Pop pop pop pop pop '
        'pop pop pop pop pop Baby gettin’ too lit rah rah rah rah rah rahHit '
        '’em up like popHit ’em with the truth like rahTime to pay your '
        'debtFear me or fear me notLet it beLet it bleedHit a lickIn a split '
        'Stop, rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock '
        'knock knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do You know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do',
  '가수': '방탄소년단',
  '곡명': '2.0',
  '발매일': '2026.03.20',
  '앨범': 'ARIRANG',
  '장르': '랩/힙합',
  '좋아요': 31800}]
===> 100 곡 노래 파싱 끝

#### song_lyric_lists를 DataFrame으로 저장하기

In [4]:
# [{'가수';'BTS','앨범':''},{}]
# columns=['곡명','가수','앨범','발매일','장르','detail_url','좋아요','가사']
import pandas as pd

#컬럼명을 설정하면서 empty DataFrame 객체생성
song_list_df = pd.DataFrame(columns=['곡명','가수','앨범','발매일','장르','detail_url','좋아요','가사'])

for song_lyric in song_lyric_list: #[ {},{},{} ]
    df_new_row = pd.DataFrame.from_records([song_lyric])
    song_list_df = pd.concat([song_list_df, df_new_row])

song_list_df.head()

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133873,Feeling love attack!I am all you needI am all ...
0,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
0,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,83080,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...
0,LEMONADE,aespa,LEMONADE - The 2nd Album,2026.05.29,일렉트로니카,https://www.melon.com/song/detail.htm?songId=6...,53934,I go in all the wayDon’t step on the brakesI t...
0,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08,댄스,https://www.melon.com/song/detail.htm?songId=6...,50447,Yeah yeah yeah yeahYeah yeah yeah yeah yeahone...

#### song_lyric_lists를 Json 파일로 저장
* json 파일로 저장해야 DataFrame으로 저장하기 용이함

In [5]:
import json

with open('data/songs100.json','w',encoding='utf-8') as file:
    json.dump(song_lyric_list, file)

### Json File을 DataFrame (표데이터) 객체로 저장하기

In [6]:
import pandas as pd

song_df = pd.read_json('data/songs100.json')
print(type(song_df))
song_df.head()

<class 'pandas.DataFrame'>

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133873,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
2,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,83080,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...
3,LEMONADE,aespa,LEMONADE - The 2nd Album,2026.05.29,일렉트로니카,https://www.melon.com/song/detail.htm?songId=6...,53934,I go in all the wayDon’t step on the brakesI t...
4,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08,댄스,https://www.melon.com/song/detail.htm?songId=6...,50447,Yeah yeah yeah yeahYeah yeah yeah yeah yeahone...

In [7]:
# 가수 별 Row Counting
print(type(song_df['가수']))
song_df['가수'].value_counts().head(10)

<class 'pandas.Series'>

가수
방탄소년단                    6
RESCENE (리센느)            4
Hearts2Hearts (하츠투하츠)    4
DAY6 (데이식스)              4
IVE (아이브)                4
aespa                    3
한로로                      3
AKMU (악뮤)                3
이무진                      3
임영웅                      3
Name: count, dtype: int64

In [8]:
# 장르 별 Row Counting
song_df['장르'].value_counts()

장르
댄스                39
발라드               23
록/메탈              11
랩/힙합               7
발라드, 국내드라마         5
인디음악, 록/메탈         4
발라드, 인디음악          3
R&B/Soul           2
애니메이션/웹툰           2
일렉트로니카             1
인디음악, 포크/블루스       1
POP                1
R&B/Soul, 인디음악     1
Name: count, dtype: int64

In [9]:
# 특정 가수의 노래 정보 출력하기
song_df.loc[song_df['가수'] == '방탄소년단','곡명':'장르']

              곡명     가수                          앨범         발매일        장르
36          SWIM  방탄소년단                     ARIRANG  2026.03.20  R&B/Soul
50      Dynamite  방탄소년단  Dynamite (DayTime Version)  2020.08.24        댄스
65            봄날  방탄소년단        YOU NEVER WALK ALONE  2017.02.13      랩/힙합
72  Body to Body  방탄소년단                     ARIRANG  2026.03.20      랩/힙합
98      Hooligan  방탄소년단                     ARIRANG  2026.03.20      랩/힙합
99           2.0  방탄소년단                     ARIRANG  2026.03.20      랩/힙합

In [10]:
# unique 한 가수명을 리스트 형태로 출력하기
song_df['가수'].unique()

<ArrowStringArray>
[          'RESCENE (리센느)',           '아이오아이 (I.O.I)',
           'CORTIS (코르티스)',                   'aespa',
              '아일릿(ILLIT)',            '태연 (TAEYEON)',
              'YENA (최예나)',             'ATEEZ(에이티즈)',
                   'WOODZ',                  '볼빨간사춘기',
                     '한로로',   'Hearts2Hearts (하츠투하츠)',
               'AKMU (악뮤)',              '화사 (HWASA)',
                     '다비치',             'DAY6 (데이식스)',
           'KiiiKiii (키키)',                   'NMIXX',
                     '최유리',               'IVE (아이브)',
               '도경수(D.O.)',              '우디 (Woody)',
                     '성시경',                    '10CM',
               'BLACKPINK',             '제니 (JENNIE)',
       'Red Velvet (레드벨벳)',                     '조째즈',
                   '방탄소년단',          '이클립스 (ECLIPSE)',
                     '이찬혁',                     '로이킴',
                 'HUNTR/X',               '로제 (ROSÉ)',
                     '이창섭',                'G-DRAGON',
                      '정국', '너드커넥션 (Nerd Connection)',
                     '이무진',                     '임영웅',
               'TWS (투어스)',                      '폴킴',
                    '카더가든',                  '프로미스나인',
                     '김나영',                'NewJeans',
                     '잔나비',                     '황가람',
                    '멜로망스',             'BOYNEXTDOOR',
          'ALLDAY PROJECT',               'Lady Gaga',
        '에픽하이 (EPIK HIGH)',                    '경서예지',
                     '임현정',                     '박다혜',
                     '박재정',      'LE SSERAFIM (르세라핌)',
          'Young K (DAY6)',                     '아이유',
                '오반(OVAN)',                   'PLAVE',
                 '순순희(지환)', 'KPop Demon Hunters Cast']
Length: 64, dtype: str

In [11]:
song_df.columns

Index(['곡명', '가수', '앨범', '발매일', '장르', 'detail_url', '좋아요', '가사'], dtype='str')

In [12]:
# pandas.core.strings.accessor.StringMethods
print(type(song_df['앨범'].str))
# print(song_df['앨범'].str.contains('OST'))

<class 'pandas.core.strings.accessor.StringMethods'>

In [13]:
# 앨범이 OST 인 노래는?
song_df.loc[song_df['앨범'].str.contains('OST'), song_df.columns.drop(['detail_url','가사'])].reset_index(drop=True)

,곡명,가수,앨범,발매일,장르,좋아요
0,너의 모든 순간,성시경,별에서 온 그대 OST Part.7,2014.02.12,"발라드, 국내드라마",325254
1,소나기,이클립스 (ECLIPSE),선재 업고 튀어 OST Part 1,2024.04.08,"발라드, 국내드라마",200456
2,사랑은 늘 도망가,임영웅,신사와 아가씨 OST Part.2,2021.10.11,"발라드, 국내드라마",238408
3,"모든 날, 모든 순간 (Every day, Every Moment)",폴킴,'키스 먼저 할까요?' OST Part.3,2018.03.20,"발라드, 국내드라마",433975
4,사랑인가 봐,멜로망스,사랑인가 봐 (사내맞선 OST 스페셜 트랙),2022.02.18,"발라드, 국내드라마",238995

### SqlAlchemy와 Pymysql을 사용하여 DataFrame을 RDB의 테이블로 저장하기

In [14]:
!pip show pymysql

Name: PyMySQL
Version: 1.2.0
Summary: Pure Python MySQL Driver
Home-page:
Author:
Author-email: Inada Naoki <songofacandy@gmail.com>, Yutaka Matsubara <yutaka.matsubara@gmail.com>
License-Expression: MIT
Location: C:\Users\Lee\anaconda3\Lib\site-packages
Requires:
Required-by:

In [15]:
%pip show sqlalchemy

Name: SQLAlchemy
Version: 2.0.51
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: c:\Users\Lee\anaconda3\Lib\site-packages
Requires: greenlet, typing-extensions
Required-by:
Note: you may need to restart the kernel to use updated packages.

### DataFrame을 Table로 저장하기

In [16]:
import pymysql

#pymysql과 sqlalchemy 연동
pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine

engine = None
conn = None
try:
    # dialect+driver://username:password@host:port/database
    engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')#, encoding='utf-8')
    print(type(engine), engine)
    conn = engine.connect()
    print(type(conn), conn)
    
    #song_df(DataFrame객체)를 songs 테이블로 저장하기 to_sql() 함수 사용    
    song_df.to_sql(name='songs', con=engine, if_exists='replace', index=False)
finally:
    if conn is not None: 
        conn.close()
    if engine is not None:
        engine.dispose()

<class 'sqlalchemy.engine.base.Engine'> Engine(mysql+pymysql://python:***@localhost:3306/python_db?charset=utf8mb4)
<class 'sqlalchemy.engine.base.Connection'> <sqlalchemy.engine.base.Connection object at 0x000001D7A7BB4980>

### 복사한 DataFrame을 Table로 저장
* 컬럼명을 영문으로 변경
* 인덱스를 1부터 시작하도록 변경하고 DataFrame 객체의 인덱스가 테이블의 PK(primary key)가 되도록 설정
* 컬럼의 데이터 타입을 변경 (발매일을 DATE 타입으로 변경)

In [17]:
# 기존의 DataFrame의 복사본을 만들기 
table_df = song_df.copy()
table_df.head(3)

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133873,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
2,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,83080,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...

In [18]:
# column명을 영문으로 다시 설정하기
table_df.columns = ['title','singer','album','release_date','genre','url','likes','lyric']
table_df.head(2)

,title,singer,album,release_date,genre,url,likes,lyric
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133873,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...

In [19]:
#index 값의 1 부터 시작하도록 설정
import numpy as np

#index 변경
table_df.index = np.arange(1, len(table_df)+1)
table_df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100],
      dtype='int64')

In [20]:
table_df.head(2)

,title,singer,album,release_date,genre,url,likes,lyric
1,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133873,Feeling love attack!I am all you needI am all ...
2,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...

In [21]:
# url 컬럼 삭제하기 axis=1은 column, axis=0 은 Row
table_df.drop('url', axis=1, inplace=False)

,title,singer,album,release_date,genre,likes,lyric
1,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,133873,Feeling love attack!I am all you needI am all ...
2,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,73354,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
3,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,83080,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...
4,LEMONADE,aespa,LEMONADE - The 2nd Album,2026.05.29,일렉트로니카,53934,I go in all the wayDon’t step on the brakesI t...
5,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08,댄스,50447,Yeah yeah yeah yeahYeah yeah yeah yeah yeahone...
...,...,...,...,...,...,...,...
96,BLACKHOLE,IVE (아이브),REVIVE+,2026.02.23,댄스,41619,"“Shall it all be sung, be done like this""너의 심장..."
97,Soda Pop,KPop Demon Hunters Cast,KPop Demon Hunters (Soundtrack from the Netfli...,2025.06.20,애니메이션/웹툰,117077,"Hey, heyHey, heyHeyDon't want you, need youYea..."
98,OVERDRIVE,TWS (투어스),play hard,2025.10.13,댄스,46824,잠깐 날 볼 때마다 놀라너무 뜨거워서 겁나이건 위험해I’m getting OVERD...
99,Hooligan,방탄소년단,ARIRANG,2026.03.20,랩/힙합,33627,"Watch this, watch this beat goin’ hooligan We ..."
100,2.0,방탄소년단,ARIRANG,2026.03.20,랩/힙합,31800,그래 방탄처럼 그게 말은 쉽지우린 뜀틀 누가 맨날 뛰어넘니웃기기는 한데 사실 안 웃...

In [22]:
#table_df.columns

#### DataFrame 객체 ==> Table 로 변환
* ['title', 'singer', 'album', 'release_date', 'genre', 'likes', 'lyric']
* table_df(DataFrame객체)를 songs100 테이블로 저장하기 to_sql() 함수 사용

In [23]:
import pymysql
import sqlalchemy

pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine

engine = None
conn = None
try:
    engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')
    conn = engine.connect()    

    table_df.to_sql(name='songs100', con=engine, if_exists='replace', index=True,\
                    index_label='id',
                    dtype={
                        'id':sqlalchemy.types.INTEGER(),
                        'title':sqlalchemy.types.VARCHAR(200),
                        'singer':sqlalchemy.types.VARCHAR(200),
                        'album':sqlalchemy.types.VARCHAR(200),
                        'release_date':sqlalchemy.types.DATE,
                        'genre':sqlalchemy.types.VARCHAR(200),
                        'likes':sqlalchemy.types.BigInteger,
                        'lyric':sqlalchemy.types.VARCHAR(5000)
                    })
    print('songs100 테이블 생성됨')
finally:
    if conn is not None: 
        conn.close()
    if engine is not None:
        engine.dispose()

songs100 테이블 생성됨

#### SQL 쿼리 결과를 DataFrame 객체로 저장하는 함수선언하기
* read_sql_query() sql문을 실행한 결과를 DataFrame 객체로 반환해주는 함수

In [24]:
def search_album(keyword):
    sql = """select * from songs100 where album like %s;"""

    import pandas as pd
    import pymysql
    import sqlalchemy

    pymysql.install_as_MySQLdb()
    from sqlalchemy import create_engine
    
    engine = None
    conn = None
    try:
        engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')
        conn = engine.connect()

        album_df = pd.read_sql_query(sql, con=conn, params=('%' + keyword + '%',))
        print(album_df.shape)
        return album_df
    finally:
        print('finally')
        if conn is not None: 
            conn.close()
        if engine is not None:
            engine.dispose()

In [25]:
search_album('OST')

(5, 9)
finally

,id,title,singer,album,release_date,genre,url,likes,lyric
0,31,너의 모든 순간,성시경,별에서 온 그대 OST Part.7,2014-02-12,"발라드, 국내드라마",https://www.melon.com/song/detail.htm?songId=4...,325254,이윽고 내가 한눈에너를 알아봤을 때모든 건 분명 달라지고 있었어내 세상은 널 알기 ...
1,38,소나기,이클립스 (ECLIPSE),선재 업고 튀어 OST Part 1,2024-04-08,"발라드, 국내드라마",https://www.melon.com/song/detail.htm?songId=3...,200456,그치지 않기를 바랬죠처음 그대 내게로 오던 그날에잠시 동안 적시는그런 비가 아니길간...
2,49,사랑은 늘 도망가,임영웅,신사와 아가씨 OST Part.2,2021-10-11,"발라드, 국내드라마",https://www.melon.com/song/detail.htm?songId=3...,238408,눈물이 난다 이 길을 걸으면그 사람 손길이 자꾸 생각이 난다붙잡지 못하고 가슴만 떨...
3,52,"모든 날, 모든 순간 (Every day, Every Moment)",폴킴,'키스 먼저 할까요?' OST Part.3,2018-03-20,"발라드, 국내드라마",https://www.melon.com/song/detail.htm?songId=3...,433975,네가 없이 웃을 수 있을까생각만 해도 눈물이 나힘든 시간 날 지켜준 사람이제는 내가...
4,67,사랑인가 봐,멜로망스,사랑인가 봐 (사내맞선 OST 스페셜 트랙),2022-02-18,"발라드, 국내드라마",https://www.melon.com/song/detail.htm?songId=3...,238995,너와 함께 하고 싶은 일들을상상하는 게요즘 내 일상이 되고너의 즐거워하는 모습을 보...